repos:
  # gitleaks (コミット対象の変更をチェック)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2  # 最新バージョンを指定
    hooks:
      - id: gitleaks
        # commit時に実行（デフォルト）
        args: [--staged]

  # TruffleHog (直前のコミット差分をチェック)
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.0
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["commit", "push"]