version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Navigating to the backend directory..."
      - cd cfa-backend
      - echo "Installing dependencies..."
      - ./gradlew clean
      - aws s3 cp s3://cfa-backend-ci/application-prod.yml src/main/resources/application-prod.yml
  build:
    commands:
      - echo "Building the backend..."
      - ./gradlew build -x test
  post_build:
    commands:
      - echo "Build completed, preparing artifacts..."
      - mkdir -p ../build-output
      - cp build/libs/*.war ../build-output/
      - cp ../codedeploy/appspec.yml ../build-output/
      - cp -r ../codedeploy/scripts/*.sh ../build-output/

artifacts:
  files:
    - build-output/**

cache:
  paths:
    - /root/.gradle/caches/**