openapi: 3.0.0

info:
  title: ColorfulAI OpenApi
  description: ""
  version: 1.0.0
  contact: {}

tags:
  - name: users
    description: ユーザーに関する事項
  - name: works
    description: 作品に関する事項
  - name: images
    description: 画像に関する事項

servers:
  - url: https://localhost:8080
    description: Local HTTPS server
  - url: http://localhost:8080
    description: Local HTTP server

paths:
  # users
  /users/token:
    $ref: "./paths/users.yaml#/UsersToken"

  /users:
    $ref: "./paths/users.yaml#/Users"

  /users/activity/search:
    $ref: "./paths/users.yaml#/UsersActivitySearch"

  /users/liked:
    $ref: "./paths/users.yaml#/UsersLiked"

  /users/liked/{workId}:
    $ref: "./paths/users.yaml#/UsersLikedByWorkId"

  /users/viewed:
    $ref: "./paths/users.yaml#/UsersViewed"

  /users/viewed/{workId}:
    $ref: "./paths/users.yaml#/UsersViewedByWorkId"

  /users/rated:
    $ref: "./paths/users.yaml#/UsersRated"

  /users/rated/{workId}:
    $ref: "./paths/users.yaml#/UsersRatedByWorkId"

  # works
  /works:
    $ref: "./paths/works.yaml#/Works"

  /works/create:
    $ref: "./paths/works.yaml#/WorksCreate"

  /works/searchByTags:
    $ref: "./paths/works.yaml#/WorksSearchByTags"

  /works/{workId}:
    $ref: "./paths/works.yaml#/WorksById"

  /works/tags:
    $ref: "./paths/works.yaml#/WorksTags"

  /works/tags/{tagId}:
    $ref: "./paths/works.yaml#/WorksTagsById"

  # images
  /images/create:
    $ref: "./paths/images.yaml#/ImagesCreate"

components:
  securitySchemes:
    AccessTokenAuth:
      type: apiKey
      name: x-access-token
      in: header
      description: Cognitoで発行したJWT
    UserTokenAuth:
      type: http
      scheme: bearer
      description: UserID等のユーザ情報を含むJWT
    CsrfTokenAuth:
      type: apiKey
      name: XSRF-TOKEN
      in: cookie
      description: CSRF保護のJWT

  schemas:
    # users
    ApiUserToken:
      $ref: "./components/schemas/users.yaml#/ApiUserToken"
  
    ApiUser:
      $ref: "./components/schemas/users.yaml#/ApiUser"

    ApiLiked:
      $ref: "./components/schemas/users.yaml#/ApiLiked"

    ApiViewed:
      $ref: "./components/schemas/users.yaml#/ApiViewed"

    ApiRated:
      $ref: "./components/schemas/users.yaml#/ApiRated"

    ApiUsersActivity:
      $ref: "./components/schemas/users.yaml#/ApiUsersActivity"

    ApiUsersActivitySearch:
      $ref: "./components/schemas/users.yaml#/ApiUsersActivitySearch"

    # works
    ApiWorkWithTag:
      $ref: "./components/schemas/works.yaml#/ApiWorkWithTag"

    ApiWork:
      $ref: "./components/schemas/works.yaml#/ApiWork"

    ApiWorkSearchByTags:
      $ref: "./components/schemas/works.yaml#/ApiWorkSearchByTags"

    ApiWorksWithSearchResult:
      $ref: "./components/schemas/works.yaml#/ApiWorksWithSearchResult"

    ApiTag:
      $ref: "./components/schemas/works.yaml#/ApiTag"

    # errors
    ApiErrorStatus:
      $ref: "./components/schemas/errors.yaml#/ApiErrorStatus"

  responses:
    # works
    WorksRegisterResponse:
      $ref: "./components/responses/works.yaml#/WorksRegisterResponse"

    WorksSearchResponse:
      $ref: "./components/responses/works.yaml#/WorksSearchResponse"

    WorksIdResponse:
      $ref: "./components/responses/works.yaml#/WorksIdResponse"

    WorksIdGetResponse:
      $ref: "./components/responses/works.yaml#/WorksIdGetResponse"

    WorksTagsResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsResponse"

    WorksTagsGetResponse:
      $ref: "./components/responses/works.yaml#/WorksTagsGetResponse"

    # errors
    BadRequestResponse:
      $ref: "./components/responses/errors.yaml#/BadRequestResponse"

    UnauthorizedResponse:
      $ref: "./components/responses/errors.yaml#/UnauthorizedResponse"
