version: 0.0
os: linux
files:
  - source: cfa-backend.war
    destination: /opt/zer0

hooks:
  BeforeInstall:
    - location: stop_application.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: start_application.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: stop_application.sh
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 30
      runas: ec2-user