services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "10000:8000"
    volumes:
      - ./data:/home/dynamodblocal/data
    environment:
      - JAVA_OPTS=-Xmx512m
      - AWS_REGION=us-east-1
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"